name: fermipy
channels:
  - conda-forge
  - fermi/label/dev
dependencies:
  - python
  - pyyaml
  - numpy>=2.0
  - scipy<1.18
  - regions<0.12
  - astropy<8
  - matplotlib>=3.3
  - healpy
  - astropy-healpix
  - gammapy>=2.0
  - fermitools>=2.2.0